name: Build and Deploy Code
run-name: ${{ github.actor }} is building and deploing code
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pullin git repo
        uses: actions/checkout@v4
      - name: Say hello to user
        run: echo "Hello ${{ github.actor }}"